"""rename_article_id_to_raw_article_id

Revision ID: dc2d6182816f
Revises: 67ad67ee951c
Create Date: 2026-03-21 19:50:32.383010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2d6182816f'
down_revision: Union[str, Sequence[str], None] = '67ad67ee951c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_metrics', sa.Column('raw_article_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_engagement_article_type'), table_name='engagement_metrics')
    op.create_index('idx_engagement_article_type', 'engagement_metrics', ['raw_article_id', 'metric_type'], unique=False)
    op.drop_constraint(op.f('engagement_metrics_article_id_fkey'), 'engagement_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'engagement_metrics', 'raw_articles', ['raw_article_id'], ['id'])
    op.drop_column('engagement_metrics', 'article_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_metrics', sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'engagement_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('engagement_metrics_article_id_fkey'), 'engagement_metrics', 'processed_articles', ['article_id'], ['id'])
    op.drop_index('idx_engagement_article_type', table_name='engagement_metrics')
    op.create_index(op.f('idx_engagement_article_type'), 'engagement_metrics', ['article_id', 'metric_type'], unique=False)
    op.drop_column('engagement_metrics', 'raw_article_id')
    # ### end Alembic commands ###
