"""baseline_complete_schema_postgres_rebuild

Revision ID: e84c51770a42
Revises: 
Create Date: 2026-02-24 08:36:35.599116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84c51770a42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_index('idx_affiliate_links_keyword', 'affiliate_links', ['keyword'], unique=False)
    op.create_table('blog_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('site_url', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform')
    )
    op.create_index('idx_blog_credentials_platform', 'blog_credentials', ['platform'], unique=False)
    op.create_table('daily_intelligence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('top_stories_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('gmail_newsletter_senders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('sample_subject', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_ai_related', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_email')
    )
    op.create_index('idx_gmail_senders_active', 'gmail_newsletter_senders', ['is_active'], unique=False)
    op.create_index('idx_gmail_senders_email', 'gmail_newsletter_senders', ['sender_email'], unique=False)
    op.create_table('hashtag_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hashtag', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hashtag_perf_platform_time', 'hashtag_performance', ['platform', 'captured_at'], unique=False)
    op.create_table('health_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_history_service', 'health_history', ['service_name', 'created_at'], unique=False)
    op.create_table('platform_roi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('total_content', sa.Integer(), nullable=False),
    sa.Column('total_chars', sa.Integer(), nullable=False),
    sa.Column('time_saved_hours', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'timestamp')
    )
    op.create_index('idx_platform_roi_platform_time', 'platform_roi', ['platform', 'timestamp'], unique=False)
    op.create_table('raw_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('is_duplicate', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_raw_articles_fetched_at', 'raw_articles', ['fetched_at'], unique=False)
    op.create_index('idx_raw_articles_state', 'raw_articles', ['state'], unique=False)
    op.create_table('rss_feeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('fetch_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_rss_feeds_active', 'rss_feeds', ['active'], unique=False)
    op.create_table('system_status',
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('service_name')
    )
    op.create_table('topic_trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('avg_viral_score', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic', 'detected_at')
    )
    op.create_index('idx_topic_trends_detected', 'topic_trends', ['detected_at'], unique=False)
    op.create_index('idx_topic_trends_topic', 'topic_trends', ['topic'], unique=False)
    op.create_table('trending_hashtags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hashtag', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashtag', 'platform')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user_styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('events', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_article_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_takeaways', sa.Text(), nullable=False),
    sa.Column('viral_score', sa.Integer(), nullable=True),
    sa.Column('tech_score', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_reason', sa.Text(), nullable=True),
    sa.Column('generated', sa.Integer(), nullable=False),
    sa.Column('llm_raw_output', sa.Text(), nullable=True),
    sa.Column('llm_validation_error', sa.Text(), nullable=True),
    sa.Column('llm_fallback', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processed_articles_raw_id', 'processed_articles', ['raw_article_id'], unique=False)
    op.create_table('rss_feed_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['rss_feeds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_id', 'guid')
    )
    op.create_index('idx_rss_feed_items_feed', 'rss_feed_items', ['feed_id'], unique=False)
    op.create_table('article_audio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('local_path', sa.String(), nullable=True),
    sa.Column('voice', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_article_audio_article', 'article_audio', ['article_id'], unique=False)
    op.create_table('article_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('local_path', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_article_images_article', 'article_images', ['article_id'], unique=False)
    op.create_table('article_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'tag')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('focus_keyword', sa.String(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('platform_slugs', sa.Text(), nullable=True),
    sa.Column('alt_text_suggestions', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('reading_time', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_table('content_hashtags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('hashtag', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'platform', 'hashtag')
    )
    op.create_index('idx_content_hashtags_article_platform', 'content_hashtags', ['article_id', 'platform'], unique=False)
    op.create_table('content_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_history_article', 'content_history', ['article_id'], unique=False)
    op.create_index('idx_content_history_timestamp', 'content_history', ['timestamp'], unique=False)
    op.create_table('engagement_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_engagement_article_type', 'engagement_metrics', ['article_id', 'metric_type'], unique=False)
    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('posted', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generated_content_article_platform', 'generated_content', ['article_id', 'platform'], unique=False)
    op.create_table('paper_analysis',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('citations_count', sa.Integer(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('affiliations', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('scheduled_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_posts_status_time', 'scheduled_posts', ['status', 'scheduled_time'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('is_positive', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_feedback_article', 'user_feedback', ['article_id'], unique=False)
    op.create_table('video_scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('visual_cues', sa.Text(), nullable=True),
    sa.Column('duration_est', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_scripts_article', 'video_scripts', ['article_id'], unique=False)
    op.create_table('blog_publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_post_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_publications')
    op.drop_index('idx_video_scripts_article', table_name='video_scripts')
    op.drop_table('video_scripts')
    op.drop_index('idx_user_feedback_article', table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index('idx_scheduled_posts_status_time', table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    op.drop_table('paper_analysis')
    op.drop_index('idx_generated_content_article_platform', table_name='generated_content')
    op.drop_table('generated_content')
    op.drop_index('idx_engagement_article_type', table_name='engagement_metrics')
    op.drop_table('engagement_metrics')
    op.drop_index('idx_content_history_timestamp', table_name='content_history')
    op.drop_index('idx_content_history_article', table_name='content_history')
    op.drop_table('content_history')
    op.drop_index('idx_content_hashtags_article_platform', table_name='content_hashtags')
    op.drop_table('content_hashtags')
    op.drop_table('blog_posts')
    op.drop_table('article_tags')
    op.drop_index('idx_article_images_article', table_name='article_images')
    op.drop_table('article_images')
    op.drop_index('idx_article_audio_article', table_name='article_audio')
    op.drop_table('article_audio')
    op.drop_index('idx_rss_feed_items_feed', table_name='rss_feed_items')
    op.drop_table('rss_feed_items')
    op.drop_index('idx_processed_articles_raw_id', table_name='processed_articles')
    op.drop_table('processed_articles')
    op.drop_table('webhooks')
    op.drop_table('user_styles')
    op.drop_table('user_preferences')
    op.drop_table('trending_hashtags')
    op.drop_index('idx_topic_trends_topic', table_name='topic_trends')
    op.drop_index('idx_topic_trends_detected', table_name='topic_trends')
    op.drop_table('topic_trends')
    op.drop_table('system_status')
    op.drop_index('idx_rss_feeds_active', table_name='rss_feeds')
    op.drop_table('rss_feeds')
    op.drop_index('idx_raw_articles_state', table_name='raw_articles')
    op.drop_index('idx_raw_articles_fetched_at', table_name='raw_articles')
    op.drop_table('raw_articles')
    op.drop_index('idx_platform_roi_platform_time', table_name='platform_roi')
    op.drop_table('platform_roi')
    op.drop_index('idx_health_history_service', table_name='health_history')
    op.drop_table('health_history')
    op.drop_index('idx_hashtag_perf_platform_time', table_name='hashtag_performance')
    op.drop_table('hashtag_performance')
    op.drop_index('idx_gmail_senders_email', table_name='gmail_newsletter_senders')
    op.drop_index('idx_gmail_senders_active', table_name='gmail_newsletter_senders')
    op.drop_table('gmail_newsletter_senders')
    op.drop_table('daily_intelligence')
    op.drop_index('idx_blog_credentials_platform', table_name='blog_credentials')
    op.drop_table('blog_credentials')
    op.drop_index('idx_affiliate_links_keyword', table_name='affiliate_links')
    op.drop_table('affiliate_links')
    # ### end Alembic commands ###
