"""sync_missing_legacy_columns

Revision ID: 8c053d5f0a83
Revises: 0e1f90079a01
Create Date: 2026-02-21 20:37:50.385006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c053d5f0a83'
down_revision: Union[str, Sequence[str], None] = '0e1f90079a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_articles', sa.Column('category', sa.String(), nullable=True))
    op.add_column('webhooks', sa.Column('events', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'events')
    op.drop_column('raw_articles', 'category')
    # ### end Alembic commands ###
