"""baseline_production

Revision ID: cf9ab5967e77
Revises: 
Create Date: 2026-02-22 00:21:12.071587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9ab5967e77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_intelligence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('top_stories_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('health_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_history_service', 'health_history', ['service_name', 'created_at'], unique=False)
    op.create_table('raw_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('is_duplicate', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_raw_articles_fetched_at', 'raw_articles', ['fetched_at'], unique=False)
    op.create_index('idx_raw_articles_state', 'raw_articles', ['state'], unique=False)
    op.create_table('system_status',
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('service_name')
    )
    op.create_table('trending_hashtags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hashtag', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashtag', 'platform')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_article_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_takeaways', sa.Text(), nullable=False),
    sa.Column('viral_score', sa.Integer(), nullable=True),
    sa.Column('tech_score', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_reason', sa.Text(), nullable=True),
    sa.Column('generated', sa.Integer(), nullable=False),
    sa.Column('llm_raw_output', sa.Text(), nullable=True),
    sa.Column('llm_validation_error', sa.Text(), nullable=True),
    sa.Column('llm_fallback', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processed_articles_raw_id', 'processed_articles', ['raw_article_id'], unique=False)
    op.create_table('article_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'tag')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('focus_keyword', sa.String(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('platform_slugs', sa.Text(), nullable=True),
    sa.Column('alt_text_suggestions', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('reading_time', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('posted', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generated_content_article_platform', 'generated_content', ['article_id', 'platform'], unique=False)
    op.create_table('paper_analysis',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('citations_count', sa.Integer(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('affiliations', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('scheduled_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_posts_status_time', 'scheduled_posts', ['status', 'scheduled_time'], unique=False)
    op.create_table('blog_publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_post_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_publications')
    op.drop_index('idx_scheduled_posts_status_time', table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    op.drop_table('paper_analysis')
    op.drop_index('idx_generated_content_article_platform', table_name='generated_content')
    op.drop_table('generated_content')
    op.drop_table('blog_posts')
    op.drop_table('article_tags')
    op.drop_index('idx_processed_articles_raw_id', table_name='processed_articles')
    op.drop_table('processed_articles')
    op.drop_table('webhooks')
    op.drop_table('user_preferences')
    op.drop_table('trending_hashtags')
    op.drop_table('system_status')
    op.drop_index('idx_raw_articles_state', table_name='raw_articles')
    op.drop_index('idx_raw_articles_fetched_at', table_name='raw_articles')
    op.drop_table('raw_articles')
    op.drop_index('idx_health_history_service', table_name='health_history')
    op.drop_table('health_history')
    op.drop_table('daily_intelligence')
    # ### end Alembic commands ###
